name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "{{ env_var('DBT_ROOT', '.') }}/target"
log-path: "{{ env_var('DBT_ROOT', '.') }}/logs"
packages-install-path: "{{ env_var('DBT_ROOT', '.') }}/dbt_packages"
clean-targets:
    - "{{ env_var('DBT_ROOT', '.') }}/target"
    - "{{ env_var('DBT_ROOT', '.') }}/dbt_packages"
    - "{{ env_var('DBT_ROOT', '.') }}/logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

seeds: 
  +docs:
    node_color: '#cd7f32'

models:
  jaffle_shop:
    materialized: table
    staging:
      materialized: view
      +docs:
        node_color: 'silver'
    +docs:
      node_color: 'gold'
